In [13]:
import numpy as np

class Solution:
    def numDecodings(self, s: str) -> int:
        if not int(s[0]):
            return 0
        if len(s) == 1:
            return 1
        dp = np.zeros(len(s)+1,dtype=int)
        dp[0] = 1
        for i in range(1,len(s)+1):
            if s[i-2:i] == '00':
                return 0
            if s[i-1:i] == '0' and s[i-2:i] > '26':
                return 0
            elif (s[i-2:i]<='26') and (s[i-2:i] >= '10' and s[i-1:i] != '0' and s[i:i+1] != '0'):
                        dp[i] =  dp[i-2] + dp[i-1]
            else:
                    dp[i] =  dp[i-1]
            print(dp)
        return dp[len(dp)-1]
            

In [15]:
instance = Solution()
s = '12120'
instance.numDecodings(s)

[1 1 0 0 0 0]
[1 1 2 0 0 0]
[1 1 2 3 0 0]
[1 1 2 3 3 0]
[1 1 2 3 3 3]


3